server:
  port: 5005
spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: TASK-USER-SERVICE
          uri:
            lb://TASK-USER-SERVICE
          predicates:
            - Path=/auth/**,/users/**,/api/users/**,/
        - id: TASKSERVICE
          uri:
            lb://TASKSERVICE
          predicates:
            - Path=/api/tasks/**,/tasks/**
        - id: SUBMISSIONSERVICE
          uri:
            lb://SUBMISSIONSERVICE
          predicates:
            - Path=/api/submissions/**,/submissions/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

