
server:
  port: 5001
spring:
  application:
    name: TaskService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/task_service
    username: root
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

